# Generated by Django 3.1.7 on 2021-11-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211116_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('mark', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='fruits',
        ),
    ]
